cp ./car_images/Abarth_500_Assetto_Corse/1.png ./docs/images/Abarth_500_Assetto_Corse.png
cp ./car_images/Alfa_Romeo_155_V6/1.png ./docs/images/Alfa_Romeo_155_V6.png
cp ./car_images/Alfa_Romeo_4C/1.png ./docs/images/Alfa_Romeo_4C.png
cp ./car_images/Alfa_Romeo_Mito_QV/1.png ./docs/images/Alfa_Romeo_Mito_QV.png
cp ./car_images/Audi_R18_etron_quattro/1.png ./docs/images/Audi_R18_etron_quattro.png
cp ./car_images/Audi_R8_LMS_2016/1.png ./docs/images/Audi_R8_LMS_2016.png
cp ./car_images/Audi_R8_LMS_ULTRA/1.png ./docs/images/Audi_R8_LMS_ULTRA.png
cp ./car_images/Audi_S1/1.png ./docs/images/Audi_S1.png
cp ./car_images/Audi_Sport_Quattro/1.png ./docs/images/Audi_Sport_Quattro.png
cp ./car_images/Audi_TT_Cup/1.png ./docs/images/Audi_TT_Cup.png
cp ./car_images/Audi_TT_RS_VLN/1.png ./docs/images/Audi_TT_RS_VLN.png
cp ./car_images/BMW_M4/1.png ./docs/images/BMW_M4.png
cp ./car_images/BMW_M4_AKRAPOVIC/1.png ./docs/images/BMW_M4_AKRAPOVIC.png
cp ./car_images/Chevrolet_Corvette_C7R/1.png ./docs/images/Chevrolet_Corvette_C7R.png
cp ./car_images/Ferrari_250_GTO/1.png ./docs/images/Ferrari_250_GTO.png
cp ./car_images/Ferrari_288_GTO/1.png ./docs/images/Ferrari_288_GTO.png
cp ./car_images/Ferrari_312_67/1.png ./docs/images/Ferrari_312_67.png
cp ./car_images/Ferrari_330_P4/1.png ./docs/images/Ferrari_330_P4.png
cp ./car_images/Ferrari_488_GT3/1.png ./docs/images/Ferrari_488_GT3.png
cp ./car_images/Ferrari_488_GTB/1.png ./docs/images/Ferrari_488_GTB.png
cp ./car_images/Ferrari_812_Superfast/1.png ./docs/images/Ferrari_812_Superfast.png
cp ./car_images/Ferrari_FXX_K/1.png ./docs/images/Ferrari_FXX_K.png
cp ./car_images/Ferrari_LaFerrari/1.png ./docs/images/Ferrari_LaFerrari.png
cp ./car_images/Ford_Escort_MK1/1.png ./docs/images/Ford_Escort_MK1.png
cp ./car_images/Ford_GT_MK1/1.png ./docs/images/Ford_GT_MK1.png
cp ./car_images/Ford_Mustang_GT/1.png ./docs/images/Ford_Mustang_GT.png
cp ./car_images/Lamborghini_Aventador_SV/1.png ./docs/images/Lamborghini_Aventador_SV.png
cp ./car_images/Lamborghini_Countach_QV5000/1.png ./docs/images/Lamborghini_Countach_QV5000.png
cp ./car_images/Lamborghini_Gallardo_SL/1.png ./docs/images/Lamborghini_Gallardo_SL.png
cp ./car_images/Lamborghini_Huracan_GT3/1.png ./docs/images/Lamborghini_Huracan_GT3.png
cp ./car_images/Lamborghini_Huracan_Performante/1.png ./docs/images/Lamborghini_Huracan_Performante.png
cp ./car_images/Lamborghini_Huracan_STO/1.png ./docs/images/Lamborghini_Huracan_STO.png
cp ./car_images/Lamborghini_Miura_SV/1.png ./docs/images/Lamborghini_Miura_SV.png
cp ./car_images/Lotus_25_SK/1.png ./docs/images/Lotus_25_SK.png
cp ./car_images/Lotus_3_eleven/1.png ./docs/images/Lotus_3_eleven.png
cp ./car_images/Lotus_72D/1.png ./docs/images/Lotus_72D.png
cp ./car_images/Maserati_250F/1.png ./docs/images/Maserati_250F.png
cp ./car_images/Maserati_Alfieri/1.png ./docs/images/Maserati_Alfieri.png
cp ./car_images/Maserati_Levante/1.png ./docs/images/Maserati_Levante.png
cp ./car_images/Maserati_MC12_GT1/1.png ./docs/images/Maserati_MC12_GT1.png
cp ./car_images/Mazda_MX5_CUP/1.png ./docs/images/Mazda_MX5_CUP.png
cp ./car_images/Mazda_MX5_NA/1.png ./docs/images/Mazda_MX5_NA.png
cp ./car_images/Mazda_RX7_Spirit_R/1.png ./docs/images/Mazda_RX7_Spirit_R.png
cp ./car_images/Mazda_RX7_Tuned/1.png ./docs/images/Mazda_RX7_Tuned.png
cp ./car_images/McLaren_570S/1.png ./docs/images/McLaren_570S.png
cp ./car_images/McLaren_650_GT3/1.png ./docs/images/McLaren_650_GT3.png
cp ./car_images/McLaren_F1_GTR/1.png ./docs/images/McLaren_F1_GTR.png
cp ./car_images/McLaren_P1/1.png ./docs/images/McLaren_P1.png
cp ./car_images/McLaren_P1_GTR/1.png ./docs/images/McLaren_P1_GTR.png
cp ./car_images/Mercedes_AMG_GT3/1.png ./docs/images/Mercedes_AMG_GT3.png
cp ./car_images/Mercedes_Benz_190_EVO2/1.png ./docs/images/Mercedes_Benz_190_EVO2.png
cp ./car_images/Mercedes_C9/1.png ./docs/images/Mercedes_C9.png
cp ./car_images/Nissan_370Z_NISMO/1.png ./docs/images/Nissan_370Z_NISMO.png
cp ./car_images/Nissan_GTR_GT3_SK/1.png ./docs/images/Nissan_GTR_GT3_SK.png
cp ./car_images/Nissan_GTR_Nismo/1.png ./docs/images/Nissan_GTR_Nismo.png
cp ./car_images/Nissan_Skyline_R34/1.png ./docs/images/Nissan_Skyline_R34.png
cp ./car_images/Pagani_Huayra_BC/1.png ./docs/images/Pagani_Huayra_BC.png
cp ./car_images/Porsche_908_LH/1.png ./docs/images/Porsche_908_LH.png
cp ./car_images/Porsche_911_GT1/1.png ./docs/images/Porsche_911_GT1.png
cp ./car_images/Porsche_911_GT3_CUP/1.png ./docs/images/Porsche_911_GT3_CUP.png
cp ./car_images/Porsche_911_GT3_R/1.png ./docs/images/Porsche_911_GT3_R.png
cp ./car_images/Porsche_911_R/1.png ./docs/images/Porsche_911_R.png
cp ./car_images/Porsche_911_RSR_2017/1.png ./docs/images/Porsche_911_RSR_2017.png
cp ./car_images/Porsche_917_30_SK/1.png ./docs/images/Porsche_917_30_SK.png
cp ./car_images/Porsche_917_K/1.png ./docs/images/Porsche_917_K.png
cp ./car_images/Porsche_918_Spyder/1.png ./docs/images/Porsche_918_Spyder.png
cp ./car_images/Porsche_919_Hybrid_2015/1.png ./docs/images/Porsche_919_Hybrid_2015.png
cp ./car_images/Porsche_935_78_Moby_Dick/1.png ./docs/images/Porsche_935_78_Moby_Dick.png
cp ./car_images/Porsche_962c_Longtail/1.png ./docs/images/Porsche_962c_Longtail.png
cp ./car_images/Porsche_962c_Shorttail/1.png ./docs/images/Porsche_962c_Shorttail.png
cp ./car_images/Porsche_991_Carrera_S/1.png ./docs/images/Porsche_991_Carrera_S.png
cp ./car_images/Porsche_991_Turbo_S/1.png ./docs/images/Porsche_991_Turbo_S.png
cp ./car_images/Porsche_Cayenne_Turbo_S/1.png ./docs/images/Porsche_Cayenne_Turbo_S.png
cp ./car_images/Porsche_Cayman_GT4_Clubsport/1.png ./docs/images/Porsche_Cayman_GT4_Clubsport.png
cp ./car_images/Porsche_Cayman_GT4_STD/1.png ./docs/images/Porsche_Cayman_GT4_STD.png
cp ./car_images/Porsche_Macan_Turbo/1.png ./docs/images/Porsche_Macan_Turbo.png
cp ./car_images/Porsche_Panamera_Turbo_2017/1.png ./docs/images/Porsche_Panamera_Turbo_2017.png
cp ./car_images/Praga_R1/1.png ./docs/images/Praga_R1.png
cp ./car_images/RUF_RT12_R_RWD/1.png ./docs/images/RUF_RT12_R_RWD.png
cp ./car_images/RUF_Yellowbird/1.png ./docs/images/RUF_Yellowbird.png
cp ./car_images/Scuderia_Glickenhaus_SCG003/1.png ./docs/images/Scuderia_Glickenhaus_SCG003.png
cp ./car_images/Toyota_AE86/1.png ./docs/images/Toyota_AE86.png
cp ./car_images/Toyota_AE86_Drift_Version/1.png ./docs/images/Toyota_AE86_Drift_Version.png
cp ./car_images/Toyota_AE86_Tuned/1.png ./docs/images/Toyota_AE86_Tuned.png
cp ./car_images/Toyota_Celica_ST185/1.png ./docs/images/Toyota_Celica_ST185.png
cp ./car_images/Toyota_GT86/1.png ./docs/images/Toyota_GT86.png
cp ./car_images/Toyota_Supra_mk_IV_Drift/1.png ./docs/images/Toyota_Supra_mk_IV_Drift.png
cp ./car_images/Toyota_Supra_mk_IV_Tuned/1.png ./docs/images/Toyota_Supra_mk_IV_Tuned.png
cp ./car_images/Toyota_TS040/1.png ./docs/images/Toyota_TS040.png
